import { ItemTravel } from '~/app/shared/types/items/item-travel.type';

export const itemTravelConst: ItemTravel[] = [
  {
    country: 'Italie',
    city: ['Florence', 'Pise'],
    picture: 'assets/travel/cities/florence.png',
    price: 190,
    duration: 4,
    durationType: 'jour',
    carbonFootprintSaved: 31.6,
    carbonFootprint: 50,
    transports: ['hike', 'bike', 'van'],
  },
  {
    country: 'Italie',
    city: ['Rome', 'Naples'],
    picture: 'assets/travel/cities/rome.jpeg',
    price: 250,
    duration: 5,
    durationType: 'jour',
    carbonFootprintSaved: 45.2,
    carbonFootprint: 60,
    transports: ['hike', 'bus', 'train'],
  },
  {
    country: 'Italie',
    city: ['Venice', 'Verona'],
    picture: 'assets/travel/cities/venice.jpeg',
    price: 220,
    duration: 3,
    durationType: 'jour',
    carbonFootprintSaved: 38.7,
    carbonFootprint: 40,
    transports: ['hike', 'train'],
  },
  {
    country: 'Italie',
    city: ['Milan', 'Turin'],
    picture: 'assets/travel/cities/milan.webp',
    price: 200,
    duration: 4,
    durationType: 'jour',
    carbonFootprintSaved: 42.3,
    carbonFootprint: 55,
    transports: ['hike', 'bus', 'van'],
  },
  {
    country: 'Italie',
    city: ['Sicily'],
    picture: 'assets/travel/cities/sicily.jpeg',
    price: 180,
    duration: 5,
    durationType: 'jour',
    carbonFootprintSaved: 36.1,
    carbonFootprint: 45,
    transports: ['hike', 'train', 'bus'],
  },
  {
    country: 'Italie',
    city: ['Genoa', 'La Spezia'],
    picture: 'assets/travel/cities/genoa.jpeg',
    price: 195,
    duration: 4,
    durationType: 'jour',
    carbonFootprintSaved: 40.0,
    carbonFootprint: 50,
    transports: ['hike', 'bike', 'train'],
  },
];
